apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  # replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: backend-api
    spec:
      containers:
        - imagePullPolicy: Always
          envFrom:
            - prefix: ''
              configMapRef:
                name: configmap-backend-api
                optional: false
          image: registry.assistx.dev/assist-tix/backend-api:latest
          name: backend-api
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: secrets-gcp-bucket-creds
              readOnly: true
              mountPath: "/secrets/gcp"
            - name: secrets-paylabs
              readOnly: true
              mountPath: "/secrets/paylabs"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
      restartPolicy: Always
      volumes:
        - name: secrets-gcp-bucket-creds
          secret:
            secretName: secrets-gcp-bucket-creds
        - name: secrets-paylabs
          secret:
            secretName: secrets-paylabs
