
services:  
  api:
    # env_file: .env.api/
    image: registry.assistx.dev/assist-tix/backend-api:staging
    ports:
      - 127.0.0.1:3010:3000
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  pgdata: