package lib

var VACodeMap = map[string]interface{}{
	"BCAVA":              nil,
	"MultipleBCAVA":      nil,
	"StaticBCAVA":        nil,
	"BNIVA":              nil,
	"MultipleBNIVA":      nil,
	"BRIVA":              nil,
	"MultipleBRIVA":      nil,
	"BSIVA":              nil,
	"MultipleBSIVA":      nil,
	"CIMBVA":             nil,
	"MultipleCIMBVA":     nil,
	"DanamonVA":          nil,
	"MultipleDanamonVA":  nil,
	"INAVA":              nil,
	"MultipleINAVA":      nil,
	"PermataVA":          nil,
	"MultiplePermataVA":  nil,
	"MandiriVA":          nil,
	"MultipleMandiriVA":  nil,
	"StaticMandiriVA":    nil,
	"MaybankVA":          nil,
	"MultipleMaybankVA":  nil,
	"MuamalatVA":         nil,
	"MultipleMuamalatVA": nil,
	"SinarmasVA":         nil,
	"MultipleSinarmasVA": nil,
}
