package dto

type PaylabsSnapCallback struct {
	PartnerServiceID        string                  `json:"partnerServiceId"`                  // M, String, 8 - Derivative of X-PARTNER-ID, similar to company code, 8 digit left padding space
	CustomerNo              string                  `json:"customerNo"`                        // M, String, 20 - Fixed value: 00000000000000000000
	VirtualAccountNo        string                  `json:"virtualAccountNo"`                  // M, String, 28 - virtualAccountNo
	VirtualAccountName      *string                 `json:"virtualAccountName,omitempty"`      // O, String, 255 - Payer. Example: Jokul Doe
	VirtualAccountEmail     *string                 `json:"virtualAccountEmail,omitempty"`     // O, String, 255 - Email
	VirtualAccountPhone     *string                 `json:"virtualAccountPhone,omitempty"`     // O, String, 30 - Mobile Phone Number, Format: 62xxxxxxxxxxxxx
	TrxID                   *string                 `json:"trxId,omitempty"`                   // C, String, 64 - Unique identifier generated by Partner
	PaymentRequestID        string                  `json:"paymentRequestId"`                  // M, String, 128 - Unique identifier generated by PJP. Platform Order Number
	ChannelCode             *int                    `json:"channelCode,omitempty"`             // O, Number, 4 - Channel code based on ISO 18245
	HashedSourceAccountNo   *string                 `json:"hashedSourceAccountNo,omitempty"`   // O, String, 32 - Source account number in hash
	SourceBankCode          *string                 `json:"sourceBankCode,omitempty"`          // O, String, 3 - Source account bank code
	PaidAmount              Amount                  `json:"paidAmount"`                        // M, Object - Paid Amount
	CumulativePaymentAmount *Amount                 `json:"cumulativePaymentAmount,omitempty"` // O, Object - Transaction Amount (cumulative)
	PaidBills               *string                 `json:"paidBills,omitempty"`               // O, String, 6 - Hexadecimal flag of paid bills
	TotalAmount             *Amount                 `json:"totalAmount,omitempty"`             // O, Object - Total transaction amount
	TrxDateTime             *string                 `json:"trxDateTime,omitempty"`             // O, Date, 25 - ISO-8601 datetime with timezone
	ReferenceNo             *string                 `json:"referenceNo,omitempty"`             // O, String, 64 - Payment auth code from PJP
	JournalNum              *string                 `json:"journalNum,omitempty"`              // O, String, 6 - Sequence journal number
	PaymentType             *string                 `json:"paymentType,omitempty"`             // O, String, 1 - Payment type
	FlagAdvise              *string                 `json:"flagAdvise,omitempty"`              // O, String, 1 - Retry notification status (N/Y)
	SubCompany              *string                 `json:"subCompany,omitempty"`              // O, String, 5 - Sub Company code
	BillDetails             *[]BillDetail           `json:"billDetails,omitempty"`             // O, Array - Max 24 bill detail objects
	BillDescription         *BillDescription        `json:"billDescription,omitempty"`         // O, Object - Bill description in English/Indonesia
	BillAmount              *Amount                 `json:"billAmount,omitempty"`              // O, Object - Bill amount
	AdditionalInfo          *AdditionalInfoCallback `json:"additionalInfo,omitempty"`          // O, Object - From Inquiry Response
	FreeTexts               *[]FreeText             `json:"freeTexts,omitempty"`               // O, Array - Max 25 free text objects
	ExtraAdditionalInfo     *ExtraAdditionalInfo    `json:"extraAdditionalInfo,omitempty"`     // O, Object - Includes fee rate, fee amount, tax, etc.
}

type AdditionalInfoCallback struct {
	BillReferenceNo *int64 `json:"billReferenceNo,omitempty"` // O, Number, 15 - Bill auth code generated by PJP
}

type ExtraAdditionalInfo struct {
	TransFeeRate   *float64 `json:"transFeeRate,omitempty"`   // O, Decimal(6,6) - Transaction rate
	TransFeeAmount *float64 `json:"transFeeAmount,omitempty"` // O, Decimal(12,2) - Transaction fee amount
	TotalTransFee  *float64 `json:"totalTransFee,omitempty"`  // O, Decimal(12,2) - Total transaction fee (excl. VAT)
	VatFee         *float64 `json:"vatFee,omitempty"`         // O, Decimal(12,2) - Taxes
	StoreID        *string  `json:"storeId,omitempty"`        // O, String, 32 - Merchant branch store ID
}
