// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "Get all paginated event",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get all paginated event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search event",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "UPCOMING",
                            "CANCELED",
                            "POSTPONED",
                            "FINISHED",
                            "ON_GOING"
                        ],
                        "type": "string",
                        "description": "Status event",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page event",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated events",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PaginatedEvents"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/events/{eventId}": {
            "get": {
                "description": "Get event By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get event By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get venue by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.DetailEventResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete event",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Delete event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/ticket-categories": {
            "get": {
                "description": "Get event By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get public ticket categories by event ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get venue by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.VenueEventTicketCategoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create event ticket category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create event ticket category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path"
                    },
                    {
                        "description": "Create event ticket category",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateEventTicketCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success create event ticket category",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/ticket-categories/{ticketCategoryId}": {
            "get": {
                "description": "Get event ticket category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get detail event ticket category by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Ticket Category ID",
                        "name": "ticketCategoryId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get venue by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.DetailEventResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/ticket-categories/{ticketCategoryId}/order": {
            "post": {
                "description": "Create event ticket transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create event ticket transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ticket Category ID",
                        "name": "ticketCategoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create event ticket transaction",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateEventTransaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.EventTransactionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/events/{eventId}/ticket-categories/{ticketCategoryId}/seatmap": {
            "get": {
                "description": "Get seatmap by event and ticket category id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get seatmap by event and ticket category id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Ticket Category ID",
                        "name": "ticketCategoryId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get seatmap",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.EventSectorSeatmapResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/organizers": {
            "get": {
                "description": "Get all organizer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizer"
                ],
                "summary": "Get all organizer",
                "responses": {
                    "200": {
                        "description": "Organizers response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.OrganizerResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create organizer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizer"
                ],
                "summary": "Create organizer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Slug",
                        "name": "slug",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Logo",
                        "name": "logo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Organizer created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/organizers/{organizerId}": {
            "get": {
                "description": "Get organizer by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizer"
                ],
                "summary": "Get organizer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organizer ID",
                        "name": "organizerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Organizer response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.OrganizerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizer"
                ],
                "summary": "Update organizer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organizer ID",
                        "name": "organizerId",
                        "in": "path"
                    },
                    {
                        "description": "Create venue request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateOrganizerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Venue created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizer"
                ],
                "summary": "Delete organizer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organizer ID",
                        "name": "organizerId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Venue created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/venues": {
            "get": {
                "description": "Get all venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "summary": "Get all venue",
                "responses": {
                    "200": {
                        "description": "List venues",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.VenueResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create venue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "summary": "Create venue",
                "parameters": [
                    {
                        "description": "Create venue request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateVenueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Venue created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}": {
            "get": {
                "description": "Get venue By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "summary": "Get venue By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get venue by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.VenueResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit venue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "summary": "Edit venue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path"
                    },
                    {
                        "description": "update venue request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVenueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Venue created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete venue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "summary": "Delete venue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}/sectors": {
            "get": {
                "description": "venue sectors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "summary": "Get venue sectors",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get venue sectors by venue id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/lib.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.VenueSectorResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateEventTicketCategoryRequest": {
            "type": "object",
            "required": [
                "code",
                "compliment_stock",
                "description",
                "name",
                "price",
                "public_stock",
                "total_compliment_stock",
                "total_public_stock",
                "total_stock",
                "venue_sector_id"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 255
                },
                "compliment_stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "description": {
                    "type": "string",
                    "example": "Ticket description"
                },
                "entrance": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "minLength": 3,
                    "example": "Ticket Reguler"
                },
                "price": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 100000
                },
                "public_stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "total_compliment_stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "total_public_stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "total_stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 10
                },
                "venue_sector_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateEventTransaction": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderItemEventTransaction"
                    }
                },
                "paymentMethod": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        },
        "dto.CreateVenueRequest": {
            "type": "object",
            "required": [
                "city",
                "country",
                "name",
                "venue_type"
            ],
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 0
                },
                "city": {
                    "type": "string",
                    "maxLength": 255
                },
                "country": {
                    "type": "string",
                    "maxLength": 255
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "venue_type": {
                    "type": "string",
                    "enum": [
                        "STADIUM",
                        "VENUE",
                        "HALL",
                        "OTHER"
                    ]
                }
            }
        },
        "dto.DetailEventPublicTicketCategoryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "entrance": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "sector": {
                    "$ref": "#/definitions/dto.TicketCategorySectorResponse"
                },
                "total_public_stock": {
                    "type": "integer"
                }
            }
        },
        "dto.DetailEventResponse": {
            "type": "object",
            "properties": {
                "active_settings": {
                    "$ref": "#/definitions/dto.EventSettingsResponse"
                },
                "additional_information": {
                    "type": "string"
                },
                "banner": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_sale_at": {
                    "type": "string"
                },
                "event_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizer": {
                    "$ref": "#/definitions/dto.SimpleOrganizerResponse"
                },
                "start_sale_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "ticket_categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EventTicketCategoryResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "venue": {
                    "$ref": "#/definitions/dto.SimpleVenueResponse"
                }
            }
        },
        "dto.EventResponse": {
            "type": "object",
            "properties": {
                "banner": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_sale_at": {
                    "type": "string"
                },
                "event_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizer": {
                    "$ref": "#/definitions/dto.SimpleOrganizerResponse"
                },
                "start_sale_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "venue": {
                    "$ref": "#/definitions/dto.SimpleVenueResponse"
                }
            }
        },
        "dto.EventSectorSeatmapResponse": {
            "type": "object",
            "properties": {
                "area_code": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "seatmap": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SectorSeatmapRowResponse"
                    }
                }
            }
        },
        "dto.EventSettingsResponse": {
            "type": "object",
            "properties": {
                "garuda_id_verification": {
                    "type": "boolean"
                },
                "max_adult_ticket_per_transaction": {
                    "type": "integer"
                }
            }
        },
        "dto.EventTicketCategoryResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "dto.EventTransactionResponse": {
            "type": "object",
            "properties": {
                "admin_fee_percentage": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "grand_total": {
                    "type": "integer"
                },
                "invoice_number": {
                    "type": "string"
                },
                "payment_expired_at": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "tax_percentage": {
                    "type": "number"
                },
                "total_admin_fee": {
                    "type": "integer"
                },
                "total_price": {
                    "type": "integer"
                },
                "total_tax": {
                    "type": "integer"
                }
            }
        },
        "dto.OrderItemEventTransaction": {
            "type": "object",
            "properties": {
                "additionalInformation": {
                    "type": "string"
                },
                "seatColumn": {
                    "type": "integer"
                },
                "seatRow": {
                    "type": "integer"
                }
            }
        },
        "dto.OrganizerResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedEvents": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EventResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.Pagination"
                }
            }
        },
        "dto.Pagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "max_page": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "dto.SectorSeatmapResponse": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.SectorSeatmapRowResponse": {
            "type": "object",
            "properties": {
                "row": {
                    "type": "integer"
                },
                "seats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SectorSeatmapResponse"
                    }
                }
            }
        },
        "dto.SimpleOrganizerResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "dto.SimpleVenueResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "venue_type": {
                    "type": "string"
                }
            }
        },
        "dto.TicketCategorySectorResponse": {
            "type": "object",
            "properties": {
                "area_code": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateOrganizerRequest": {
            "type": "object",
            "required": [
                "name",
                "slug"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "slug": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "dto.UpdateVenueRequest": {
            "type": "object",
            "required": [
                "city",
                "country",
                "is_active",
                "name",
                "venue_type"
            ],
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 0
                },
                "city": {
                    "type": "string",
                    "maxLength": 255
                },
                "country": {
                    "type": "string",
                    "maxLength": 255
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "venue_type": {
                    "type": "string",
                    "enum": [
                        "STADIUM",
                        "VENUE",
                        "HALL",
                        "OTHER"
                    ]
                }
            }
        },
        "dto.VenueEventTicketCategoryResponse": {
            "type": "object",
            "properties": {
                "ticket_categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DetailEventPublicTicketCategoryResponse"
                    }
                },
                "venue": {
                    "$ref": "#/definitions/dto.VenueResponse"
                }
            }
        },
        "dto.VenueResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "venue_type": {
                    "type": "string"
                }
            }
        },
        "dto.VenueSectorResponse": {
            "type": "object",
            "properties": {
                "area_code": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "has_seatmap": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "sector_color": {
                    "type": "string"
                },
                "sector_column": {
                    "type": "integer"
                },
                "sector_row": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "lib.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "default": true
                }
            }
        },
        "lib.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "default": false
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Assist Tix Documentation",
	Description:      "Assist Tix API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
